name: quiz_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Use firebase_core version compatible with cloud_firestore version below.
  firebase_core: ^2.0.0
  # Upgraded cloud_firestore to a version that works with firebase_core ^2.0.0.
  cloud_firestore: ^4.17.5
  
  # HTTP package to fetch data from the API
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
