// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4UvBmjE9uivPGk-a7URC4ngn905EeLRs',
    appId: '1:755954504927:web:9846bcb5ca0ec344efc56a',
    messagingSenderId: '755954504927',
    projectId: 'quizapp-e4ba2',
    authDomain: 'quizapp-e4ba2.firebaseapp.com',
    storageBucket: 'quizapp-e4ba2.firebasestorage.app',
    measurementId: 'G-SYPD9CNGFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiOZLJLiSroex2lErtNtg30wTHofPL3-w',
    appId: '1:755954504927:android:5ed72d97a9f74079efc56a',
    messagingSenderId: '755954504927',
    projectId: 'quizapp-e4ba2',
    storageBucket: 'quizapp-e4ba2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzmorOmzhS-8jVGhtdJeoX3QCrk6N222I',
    appId: '1:755954504927:ios:1a3f950435a549f3efc56a',
    messagingSenderId: '755954504927',
    projectId: 'quizapp-e4ba2',
    storageBucket: 'quizapp-e4ba2.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzmorOmzhS-8jVGhtdJeoX3QCrk6N222I',
    appId: '1:755954504927:ios:1a3f950435a549f3efc56a',
    messagingSenderId: '755954504927',
    projectId: 'quizapp-e4ba2',
    storageBucket: 'quizapp-e4ba2.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4UvBmjE9uivPGk-a7URC4ngn905EeLRs',
    appId: '1:755954504927:web:f28a405bc39e8776efc56a',
    messagingSenderId: '755954504927',
    projectId: 'quizapp-e4ba2',
    authDomain: 'quizapp-e4ba2.firebaseapp.com',
    storageBucket: 'quizapp-e4ba2.firebasestorage.app',
    measurementId: 'G-L3P7JY9RB0',
  );
}
